name: Regression End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
         command: npm run test:addToCart    

      - name: Cypress Test Report
        if: always()
        uses: actions/checkout@v3
        with:
          name: Mochawesome HTML Report
          path: cypress/reports/html   
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Automation report https://github.com/MithilaA/Cypress_framework_from_scratch/actions/runs/${{github.run_id}}'
          SLACK_TITLE: Cypress Report
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}