name: Parallel exection End-to-end tests
on: push
jobs:
  add_to_cart-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:add_to_cart
      - name: Cypress Test Report
        if: always()
        uses: actions/checkout@v4
        with:
          name: Mochawesome_HTML_Report-add_to_cart
          path: cypress/reports/html
 
 
 
  register-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:register_user
      - name: Cypress Test Report
        if: always()
        uses: actions/upload-artifact@v3 
        with:
          name: Mochawesome_HTML_Report-Register
          path: cypress/reports/html
        